///usr/bin/env jbang "$0" "$@" ; exit $?
//SOURCES ../../sdk/java/src/main/java/com/hayden/testgraphsdk/sdk/*.java
//SOURCES ../home-clone/HomeCloneSupport.java

import com.hayden.testgraphsdk.sdk.Node;
import com.hayden.testgraphsdk.sdk.NodeResult;
import com.hayden.testgraphsdk.sdk.NodeSpec;
import com.hayden.testgraphsdk.sdk.ProcessRecord;
import com.hayden.testgraphsdk.sdk.Procs;

import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.List;

/**
 * Provisions the cloned home's launch surface with {@code home shims} — and
 * nothing else — then asserts what that command alone is contracted to produce.
 *
 * <h2>"And nothing else" is the whole point of this node</h2>
 *
 * <p>Issue #61: every home on the reporting machine that had a working launcher
 * got it from {@code git-integration-repo}'s {@code bootstrap-home.sh}, whose
 * {@code ensure_cli_pin} wrote an absolute CLI pin over the shim
 * {@code home shims} had just written. Twenty-four repositories were onboarded
 * through that script, so the defect in {@code home shims} was masked
 * everywhere it existed. This node runs {@code home shims} on a bare clone with
 * no repair step behind it, which is the only arrangement in which the command's
 * own output is what is being judged.
 *
 * <h2>What the first two versions of this node got wrong</h2>
 *
 * <p>The first version asserted the CLI entrypoint directly on a fresh clone and
 * failed. That reproduced issue #10's second defect, but mis-stated it:
 * {@code home clone} copies and re-anchors whatever {@code bin/} the SOURCE had;
 * it does not invent a launch surface. The real defect was narrower and worse —
 * {@code <home>/bin/cli/skill-manager} had TWO readers (the launcher script and
 * {@code HomeDescriptor.resolveCli}) and NO writer. {@code home shims} now
 * writes it alongside the launchers.
 *
 * <p>The second version asserted that the entrypoint {@code exec}s "the CLI it
 * finds on PATH", with a stub planted on PATH to be found. That case passed
 * happily while the shipped behaviour was broken, because the assertion had
 * adopted the defect as its specification. On a real machine the thing found on
 * {@code PATH} is the globally installed release, which had no {@code exec}
 * subcommand at all — so the launcher's last line,
 * {@code exec "$cli" exec --home ...}, produced
 * {@code Unmatched arguments: 'exec'} on every home this command provisioned.
 *
 * <h2>So the PATH stub is now a DECOY, and finding it is the failure</h2>
 *
 * <p>Every runtime case below plants a working, executable {@code skill-manager}
 * first on {@code PATH} — the stand-in for {@code /opt/homebrew/bin/skill-manager}
 * — and asserts the shim ignored it. A decoy that succeeds is deliberate: a
 * decoy that failed would let a shim pass by accident, whereas this one makes
 * "the shim did not consult PATH" the only explanation for its sentinel being
 * absent. The succeeding direction is asserted on the exec'd CLI's OUTPUT, never
 * on a zero exit, because a shim that exits 0 without launching is the failure
 * #10 named.
 *
 * <h2>The refusal case is a STALE pin, not an absent CLI</h2>
 *
 * <p>"Nothing is reachable" is no longer an interesting arrangement: the shim
 * does not search, so it cannot be affected by what is or is not on PATH. What
 * can go wrong is that the pinned build moves or is deleted, and the contract
 * for that is a loud 127 naming the path — never a quiet fall-through to
 * whatever is installed. The case is built by taking the generated bytes and
 * repointing the pin at a path that does not exist, so it exercises the shipped
 * script rather than a hand-written imitation of it.
 *
 * <h2>Percent escaping, still asserted on bytes</h2>
 *
 * <p>{@code cliScript} once emitted {@code printf '%%s'} — correct in
 * {@code script(String)}, which ends in {@code .formatted(agent)}, and wrong
 * there, where nothing unescaped it. The filtered PATH became the single entry
 * {@code %s} and the shim refused UNCONDITIONALLY, on seven onboarded homes,
 * while this node reported {@code refusalExitCode: 127} and passed. The byte
 * assertion is the cheapest place to catch the next copy-paste and it names the
 * cause rather than a symptom, so it stays.
 */
public class CheckoutHomeProvisioned {
    static final NodeSpec SPEC = NodeSpec.of("checkout.home.provisioned")
            .kind(NodeSpec.Kind.ACTION)
            .dependsOn("home.cloned.into.project")
            .tags("checkout-home", "home", "shims")
            // Three bounded shim invocations plus `home shims` itself. The
            // per-invocation bound (BOUND_SECONDS) is what turns a self-exec
            // spin into a NAMED failure; this is only the outer backstop, so it
            // has to be comfortably larger than 3 x that bound rather than
            // tighter than it.
            .timeout("600s");

    public static void main(String[] args) {
        Node.run(args, SPEC, ctx -> {
            String store = ctx.get("home.clone.fixture.built", "cloneStore").orElse(null);
            if (store == null) {
                return NodeResult.fail("checkout.home.provisioned", "missing upstream context");
            }
            Path home = Path.of(store);

            ProcessRecord shims =
                    HomeCloneSupport.sm(ctx, "home-shims", store, "home", "shims", "--home", store);
            boolean homeShimsExitsZero = shims.exitCode() == 0;

            Path cli = home.resolve("bin").resolve("cli").resolve("skill-manager");
            boolean theCliEntrypointWasWritten = Files.exists(cli, LinkOption.NOFOLLOW_LINKS);
            boolean theCliEntrypointIsExecutable = Files.isExecutable(cli);

            List<String> launchers = HomeCloneSupport.names(home.resolve("bin").resolve("launch"));
            boolean everyAgentLauncherWasWritten =
                    launchers.containsAll(List.of("claude", "codex", "gemini"));

            String body = HomeCloneSupport.read(cli);

            // Still relocatable in the sense that matters: the HOME is derived
            // from the shim's own location, so a copied home binds itself. Only
            // the CLI is absolute.
            boolean theCliEntrypointCarriesNoAbsoluteHomePath =
                    !body.isBlank() && !body.contains(store);

            // A doubled percent in a body with no `.formatted()` reaches bash
            // literally. Asserted on the generated BYTES because that is the
            // cheapest place to catch the next copy-paste from `script(String)`.
            boolean theCliEntrypointCarriesNoUnformattedPercent = !body.contains("%%");

            // The pin, by identity: the CLI this graph ran `home shims` WITH is
            // the CLI the home must now be bound to. Nothing else would do —
            // "some absolute path" would be satisfied by a pin to the wrong build.
            String wroteIt = HomeCloneSupport.skillManager().toAbsolutePath().normalize().toString();
            boolean theCliEntrypointPinsTheBuildThatWroteIt = body.contains(wroteIt);
            boolean theCliEntrypointAsksNoPathQuestion = !body.contains("command -v");
            boolean theCliEntrypointRebindsTheHome =
                    body.contains("export SKILL_MANAGER_HOME=\"$home\"");

            // The stable token another tool keys on. `ensure_cli_pin` decided
            // whether to overwrite this file by grepping it for the words
            // `home shims` — which every version of it contains — and so
            // overwrote correct pins on 17 of 25 homes.
            boolean theCliEntrypointCarriesTheStablePinMarker =
                    body.contains("skill-manager:cli-pin");

            Path sandbox = Files.createTempDirectory("checkout-home-cli-");
            Path decoy = decoyOnPath(sandbox);

            // The INHERITED PATH is kept behind the decoy on purpose. A hermetic
            // PATH would make these cases pass on a machine where nothing else
            // could have been found, which is precisely the condition that does
            // not hold on the machine where #61 was reported: there the real
            // `skill-manager` is on PATH ahead of everything, and the pinned CLI
            // is a jbang launcher that needs the rest of PATH to run at all. So
            // the arrangement here is the real one — a working, wrong CLI first,
            // an ordinary PATH behind it — and the decoy's absence from the
            // output is the evidence.
            String inherited = System.getenv("PATH") == null ? "" : ":" + System.getenv("PATH");

            // (1) A WORKING skill-manager first on PATH. The shim must run its
            // pin instead. Proven from output: the pinned build prints its own
            // launcher path under `--version` (BuildIdentity), which is exactly
            // the disambiguation that did not exist when #61 was reported —
            // both builds answered `skill-manager 0.19.2` and nothing else.
            Run pinned = run(ctx, "cli-with-a-decoy-first-on-path", cli,
                    decoy + inherited, sandbox);
            boolean theCliEntrypointExecsItsPinNotPath =
                    pinned.exit() == 0
                            && pinned.out().contains(wroteIt)
                            && !pinned.out().contains(DECOY_SENTINEL);

            // (2) The shim's own directory first on PATH, as LaunchEnv arranges
            // a launch, with the decoy behind it. Kept from the version that
            // guarded an unbounded self-exec: the shim no longer searches, so it
            // cannot find itself, and this asserts that the property survived
            // rather than assuming it did.
            Run selfFirst = run(ctx, "cli-with-self-first-on-path", cli,
                    cli.getParent() + ":" + decoy + inherited, sandbox);
            boolean theCliEntrypointNeverResolvesToItself =
                    !selfFirst.timedOut() && selfFirst.exit() == 0
                            && selfFirst.out().contains(wroteIt);

            // (3) A STALE pin, with the decoy still first on PATH. The shipped
            // bytes with one substitution, so what runs is the generated script.
            Path stale = staleCopy(sandbox, body, wroteIt);
            Run refusal = run(ctx, "cli-with-a-stale-pin", stale, decoy + inherited, sandbox);
            boolean theCliEntrypointRefusesAStalePinRatherThanFallingBack =
                    refusal.exit() == 127
                            && refusal.out().contains("the CLI pinned for the home at")
                            && !refusal.out().contains(DECOY_SENTINEL);

            boolean pass = homeShimsExitsZero && theCliEntrypointWasWritten
                    && theCliEntrypointIsExecutable && everyAgentLauncherWasWritten
                    && theCliEntrypointCarriesNoAbsoluteHomePath
                    && theCliEntrypointCarriesNoUnformattedPercent
                    && theCliEntrypointPinsTheBuildThatWroteIt
                    && theCliEntrypointAsksNoPathQuestion
                    && theCliEntrypointRebindsTheHome
                    && theCliEntrypointCarriesTheStablePinMarker
                    && theCliEntrypointExecsItsPinNotPath
                    && theCliEntrypointNeverResolvesToItself
                    && theCliEntrypointRefusesAStalePinRatherThanFallingBack;

            return (pass
                    ? NodeResult.pass("checkout.home.provisioned")
                    : NodeResult.fail("checkout.home.provisioned",
                            "shimsExit=" + shims.exitCode() + " cli=" + cli
                                    + " exists=" + theCliEntrypointWasWritten
                                    + " launchers=" + launchers
                                    + " pinnedTo=" + wroteIt
                                    + " noAbsolutePath=" + theCliEntrypointCarriesNoAbsoluteHomePath
                                    + " noDoubledPercent="
                                    + theCliEntrypointCarriesNoUnformattedPercent
                                    + " pinsWriter=" + theCliEntrypointPinsTheBuildThatWroteIt
                                    + " noPathQuestion=" + theCliEntrypointAsksNoPathQuestion
                                    + " rebindsHome=" + theCliEntrypointRebindsTheHome
                                    + " pinned=" + pinned
                                    + " selfFirst=" + selfFirst
                                    + " refusal=" + refusal))
                    .assertion("home_shims_exits_zero", homeShimsExitsZero)
                    .assertion("the_cli_entrypoint_was_written", theCliEntrypointWasWritten)
                    .assertion("the_cli_entrypoint_is_executable", theCliEntrypointIsExecutable)
                    .assertion("every_agent_launcher_was_written", everyAgentLauncherWasWritten)
                    .assertion("the_cli_entrypoint_carries_no_absolute_home_path",
                            theCliEntrypointCarriesNoAbsoluteHomePath)
                    .assertion("the_cli_entrypoint_carries_no_unformatted_percent",
                            theCliEntrypointCarriesNoUnformattedPercent)
                    .assertion("the_cli_entrypoint_pins_the_build_that_wrote_it",
                            theCliEntrypointPinsTheBuildThatWroteIt)
                    .assertion("the_cli_entrypoint_asks_no_path_question",
                            theCliEntrypointAsksNoPathQuestion)
                    .assertion("the_cli_entrypoint_rebinds_the_home",
                            theCliEntrypointRebindsTheHome)
                    .assertion("the_cli_entrypoint_carries_the_stable_pin_marker",
                            theCliEntrypointCarriesTheStablePinMarker)
                    .assertion("the_cli_entrypoint_execs_its_pin_not_path",
                            theCliEntrypointExecsItsPinNotPath)
                    .assertion("the_cli_entrypoint_never_resolves_to_itself",
                            theCliEntrypointNeverResolvesToItself)
                    .assertion("the_cli_entrypoint_refuses_a_stale_pin_rather_than_falling_back",
                            theCliEntrypointRefusesAStalePinRatherThanFallingBack)
                    .metric("refusalExitCode", refusal.exit())
                    .process(shims);
        });
    }

    /**
     * Printed by the DECOY on PATH. Finding it anywhere in a shim's output is
     * issue #61 reproducing.
     */
    private static final String DECOY_SENTINEL = "DECOY-ON-PATH-WAS-EXECED";

    /**
     * How long a shim invocation may take before it is treated as recursion.
     * Generous because the pinned CLI is a jbang launcher and may compile on a
     * cold cache; the bound exists to convert a spin into a named failure, not
     * to police latency.
     */
    private static final long BOUND_SECONDS = 120;

    private record Run(int exit, String out, boolean timedOut) {
        @Override
        public String toString() {
            return "{exit=" + exit + " timedOut=" + timedOut
                    + " out=" + out.replace('\n', '|').trim() + "}";
        }
    }

    /**
     * Run the shim with {@code path} as its whole PATH, bounded.
     *
     * <p>Bounded rather than left to the node timeout because the failure this
     * is guarding is an unbounded self-exec: a node timeout reports "the node
     * took too long", while this reports which invocation spun and with what
     * PATH. Spawned by hand rather than through {@code Procs.run} for the same
     * reason — that helper's {@code waitFor()} has no bound.
     */
    private static Run run(com.hayden.testgraphsdk.sdk.NodeContext ctx, String label, Path cli,
                           String path, Path cwd) throws Exception {
        Path log = Procs.logFile(ctx, label);
        ProcessBuilder pb = new ProcessBuilder(cli.toString(), "--version");
        pb.directory(cwd.toFile());
        pb.environment().remove("SKILL_MANAGER_CLI");
        pb.environment().put("PATH", path);
        pb.redirectErrorStream(true).redirectOutput(log.toFile());
        Process proc = pb.start();
        boolean finished = proc.waitFor(BOUND_SECONDS, java.util.concurrent.TimeUnit.SECONDS);
        if (!finished) {
            proc.descendants().forEach(ProcessHandle::destroyForcibly);
            proc.destroyForcibly();
            proc.waitFor();
            return new Run(-1, HomeCloneSupport.read(log), true);
        }
        return new Run(proc.exitValue(), HomeCloneSupport.read(log), false);
    }

    /**
     * A PATH directory holding a working {@code skill-manager} that is NOT the
     * one the home was pinned to — the stand-in for the globally installed
     * release that issue #61 was actually reaching.
     *
     * <p>It exits 0 on purpose. A decoy that failed would let a shim pass by
     * accident; a decoy that succeeds makes its own absence from the output the
     * evidence.
     */
    private static Path decoyOnPath(Path sandbox) throws Exception {
        Path dir = Files.createDirectories(sandbox.resolve("decoy-bin"));
        Path decoy = dir.resolve("skill-manager");
        Files.writeString(decoy, """
                #!/bin/sh
                echo "%s"
                exit 0
                """.formatted(DECOY_SENTINEL));
        decoy.toFile().setExecutable(true, false);
        return dir;
    }

    /**
     * The generated script, byte for byte, with its pin repointed at a path that
     * does not exist.
     *
     * <p>A copy rather than an edit of the home's own file: the later graph
     * nodes assert on that home, and a test that breaks its own fixture to make
     * a point is a test that has moved the failure somewhere else.
     */
    private static Path staleCopy(Path sandbox, String body, String pinnedTo) throws Exception {
        Path dir = Files.createDirectories(sandbox.resolve("stale-home/bin/cli"));
        Path stale = dir.resolve("skill-manager");
        Files.writeString(stale, body.replace(pinnedTo, sandbox.resolve("deleted-build").toString()));
        stale.toFile().setExecutable(true, false);
        return stale;
    }
}
