#!/usr/bin/env bash
# Smoke fixture for the skill-script CLI backend. Drops a sentinel file
# (an empty executable) into $SKILL_MANAGER_BIN_DIR so the smoke node
# can assert the script ran end-to-end without needing a real toolchain.
#
# Verifies the contract that the backend sets the env vars the docs
# promise — fails loudly if any are missing rather than silently
# touching nothing.
set -euo pipefail

: "${SKILL_MANAGER_BIN_DIR:?SKILL_MANAGER_BIN_DIR is required}"
: "${SKILL_MANAGER_CACHE_DIR:?SKILL_MANAGER_CACHE_DIR is required}"
: "${SKILL_DIR:?SKILL_DIR is required}"
: "${SKILL_SCRIPTS_DIR:?SKILL_SCRIPTS_DIR is required}"
: "${SKILL_NAME:?SKILL_NAME is required}"

# ARTI-08. The sentinel used to be an empty file in bin/, which is exactly the
# half `PruneCliIfOrphan` already removed — so the node built on it could not
# see the half that survives an uninstall. A real skill-script install writes a
# TREE under $SKILL_MANAGER_CACHE_DIR and leaves a wrapper that execs into it
# (`cache/skill-script-deploy-helm-helm-deploy/venv/bin/helm-deploy` in the
# operator's home), and the tree is what outlived its owner forever.
tree="$SKILL_MANAGER_CACHE_DIR/skill-script-$SKILL_NAME-skill-script-touched"
mkdir -p "$tree/venv/bin"
printf '#!/bin/sh\necho skill-script-touched\n' > "$tree/venv/bin/skill-script-touched"
chmod +x "$tree/venv/bin/skill-script-touched"

# HBR-1. The tree's path RELATIVE TO A HOME. This fixture used to bake the
# absolute one into the wrapper, which is the frozen shape ShimHomeContract
# refuses: copied into another home, the wrapper went on running THIS home's
# tree while the other home's own sat unused. A fixture that keeps the frozen
# shape is a fixture that defends the bug, so it moves with the contract.
home="$(cd -- "${SKILL_MANAGER_HOME:-$SKILL_MANAGER_BIN_DIR/../..}" && pwd -P)"
tree_real="$(cd -- "$tree" && pwd -P)"
case "$tree_real" in
  "$home"/*) rel="${tree_real#"$home"/}/venv/bin/skill-script-touched" ;;
  *)
    echo "skill-script-skill: \$SKILL_MANAGER_CACHE_DIR ($tree) is not inside the home at $home" >&2
    exit 1
    ;;
esac

mkdir -p "$SKILL_MANAGER_BIN_DIR"
# A generated wrapper, not an empty file: it is the wrapper's own bytes that
# name the tree, which is the only evidence a home has of which install wrote
# a directory (ArtifactBackfill.provisionedTrees). The name is home-relative
# now, and `HomeCloner.referencesIn` reads that shape for exactly this reason —
# a contract that cost a home the ability to prune its own trees would have
# reopened skill-manager#104 for every installer that complied with it.
cat > "$SKILL_MANAGER_BIN_DIR/skill-script-touched" <<SH
#!/usr/bin/env bash
# Generated by test_graph/fixtures/skill-script-skill/skill-scripts/install.sh.
set -euo pipefail
rel="$rel"
SH
cat >> "$SKILL_MANAGER_BIN_DIR/skill-script-touched" <<'SH'
shim_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
home="$(cd -- "$shim_dir/../.." && pwd -P)"
target="$home/$rel"
if [ ! -x "$target" ]; then
  # The sanctioned fallback: this home provisioned no tree of its own, so
  # follow the link this shim came in on rather than storing a path that a
  # home WITH its own tree would then take.
  link="${BASH_SOURCE[0]}"
  for _ in 1 2 3 4 5 6 7 8; do
    [ -L "$link" ] || break
    t="$(readlink "$link")"
    case "$t" in
      /*) link="$t" ;;
      *)  link="$(cd -- "$(dirname -- "$link")" && pwd -P)/$t" ;;
    esac
    pinned="$(cd -- "$(dirname -- "$link")/../.." 2>/dev/null && pwd -P)" || continue
    if [ -x "$pinned/$rel" ]; then target="$pinned/$rel"; break; fi
  done
fi
exec "$target" "$@"
SH
chmod +x "$SKILL_MANAGER_BIN_DIR/skill-script-touched"

# Diagnostic breadcrumb — surfaces in node-logs/ if the assertion fails.
echo "skill-script-skill: touched $SKILL_MANAGER_BIN_DIR/skill-script-touched and $tree (skill=$SKILL_NAME)"
