#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["PyYAML>=6.0.2,<7"]
# ///
"""Regenerate the epic's validation projection from the canonical ticket plan.

WHY THIS EXISTS
---------------
`validate_epic_plan.py` requires full epic scheduling fields — wave,
promotion_order, blocks, conflict_keys, goals — on EVERY ticket in a file. This
repository's plan also carries 34 pre-epic CHM/COH/EFF/ISSUE/MIG tickets that
predate the epic primitive and legitimately have none, so validating the whole
file reports those 34 and buries the epic's own findings.

The projection is the workaround: the epic blocks plus the HIS-* tickets only.
It is also a trap, and the trap sprang once already. A projection generated by
hand at kickoff went stale within a wave — HIS-1 and HIS-2 still `next`/`planned`
after delivery, HIS-4 still `github_issue: null` after being bound to #216 and
rescoped, and a `conflict_keys.test_graph` naming a node that was never written.
Because the projection is what the validator actually runs against, a stale copy
does not fail; it silently validates a schedule nobody is working to.

So regeneration is a command rather than a habit. Run it after any schedule
change, and in CI with `--check` so drift is caught rather than remembered.

    .github/scripts/regen-epic-projection.py
    .github/scripts/regen-epic-projection.py --check    # non-zero if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
PLAN = REPO / "specs" / "desired_program_model" / "ticket_plan.yaml"
OUT = (REPO / "results" / "epic-home-integrity-sync" / "validation"
       / "epic_plan_projection.yaml")

PREFIX = "HIS-"

NOTE = (
    "GENERATED PROJECTION -- do not hand-edit, and REGENERATE IT AFTER EVERY SCHEDULE "
    "CHANGE with .github/scripts/regen-epic-projection.py. Extracted from "
    "specs/desired_program_model/ticket_plan.yaml, which is canonical. It carries the "
    "epic blocks and only the HIS-* tickets, because validate_epic_plan.py requires full "
    "epic scheduling fields on EVERY ticket in a file and the pre-epic "
    "CHM/COH/EFF/ISSUE/MIG tickets legitimately have none. A stale projection is worse "
    "than no projection: it is what validate_epic_plan.py actually runs against, so an "
    "unregenerated copy silently validates a schedule nobody is working to. That happened "
    "once, between wave 1 and wave 2, which is why this file is generated and checkable."
)

ROOT_KEYS = ("version", "schedule_revision", "name", "epic",
             "deferment_policy", "review_policy", "epic_goals")


def build() -> str:
    plan = yaml.safe_load(PLAN.read_text())
    proj = {k: plan[k] for k in ROOT_KEYS if k in plan}
    proj["tickets"] = [t for t in plan["tickets"]
                       if str(t.get("id", "")).startswith(PREFIX)]
    proj["_note"] = NOTE
    return yaml.safe_dump(proj, sort_keys=False, width=100, allow_unicode=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the projection on disk is stale")
    args = ap.parse_args()

    rendered = build()
    current = OUT.read_text() if OUT.is_file() else None

    if args.check:
        if current == rendered:
            print(f"ok    {OUT.relative_to(REPO)} is current")
            return 0
        print(f"STALE {OUT.relative_to(REPO)} does not match "
              f"{PLAN.relative_to(REPO)}", file=sys.stderr)
        print("      regenerate: .github/scripts/regen-epic-projection.py",
              file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    n = len(yaml.safe_load(rendered)["tickets"])
    print(f"wrote {OUT.relative_to(REPO)} ({n} {PREFIX}* ticket(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
