package dev.skillmanager.project;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import dev.skillmanager.agent.AgentHomes;
import dev.skillmanager.model.AgentUnit;
import dev.skillmanager.model.UnitKind;
import dev.skillmanager.shared.util.Fs;
import dev.skillmanager.store.SkillStore;
import dev.skillmanager.store.UnitReadProblem;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Skill-manager-owned local marketplace that wraps every installed plugin
 * for harness CLIs ({@code claude plugin}, {@code codex plugin marketplace}).
 *
 * <p>The marketplace lives at {@code <store>/plugin-marketplace/} and is
 * one shared root for all harnesses — Claude and Codex each register the
 * same path via {@code plugin marketplace add <path>}, then their CLIs
 * read {@code .claude-plugin/marketplace.json} from inside it.
 *
 * <p>Each installed plugin is exposed as a per-plugin symlink under
 * {@code plugin-marketplace/plugins/<name>} → {@code <store>/plugins/<name>},
 * and a corresponding {@code plugins[].source} entry in
 * {@code marketplace.json} points at the relative path
 * {@code "./plugins/<name>"}. The symlink keeps the plugin bytes
 * single-source (the store) while letting the harness CLIs resolve a
 * stable layout under the marketplace root.
 *
 * <p>Regeneration is idempotent — call {@link #regenerate()} after any
 * change to the installed-plugin set and the marketplace root will end
 * up consistent: stale symlinks pruned, manifest rewritten, missing
 * symlinks recreated. Skills are ignored — the harness CLIs only deal
 * with plugins.
 *
 * <p><b>Idempotent is not the same as knowing.</b> This regenerates the
 * manifest and the whole symlink tree on every pass precisely because nothing
 * recorded what the last pass generated them from, so "did the installed plugin
 * set change" could not be asked. {@link #regenerate()} now writes
 * {@link MarketplaceInputs} beside the tree — one graded input fingerprint per
 * entry, over the entry's identity and the plugin's bytes in the store — which
 * is what makes the question answerable at all. It does not yet SKIP the
 * regeneration on a match: doing so is a behaviour change with its own
 * failure modes (a hand-edited manifest would stop being repaired), and this
 * records the fact a later short-circuit needs rather than assuming it.
 */
public final class PluginMarketplace {

    /**
     * Marketplace identifier for the OPERATOR ROOT home only. Harness CLIs
     * (codex in particular) key marketplaces globally by name, so every
     * other home derives a per-home name via {@link #name()} — two
     * per-checkout homes registering under one shared name fight over a
     * single config slot, and the loser's plugins become uninstallable
     * ("plugin X was not found in marketplace skill-manager").
     */
    public static final String NAME = "skill-manager";

    private static final String DESCRIPTION =
            "Local marketplace generated by skill-manager. "
            + "Contains every plugin installed via skill-manager.";

    private final SkillStore store;
    private final ObjectMapper json = new ObjectMapper()
            .enable(SerializationFeature.INDENT_OUTPUT);

    public PluginMarketplace(SkillStore store) {
        this.store = store;
    }

    /**
     * The identity this home's marketplace registers under. The operator
     * root home keeps the bare {@link #NAME} (existing operator setups and
     * assertions depend on it); every other home appends a stable
     * fingerprint of its store root, so concurrent per-checkout homes get
     * disjoint config slots instead of destructively re-pointing one.
     */
    public String name() {
        Path root = store.root();
        // Anchor on the literal user home, NOT agentHomeRoot(): the latter
        // follows SKILL_MANAGER_HOME, under which every per-checkout home
        // would consider itself "the root" and take the shared name back.
        Path operatorRoot = Path.of(System.getProperty("user.home"))
                .resolve(AgentHomes.STORE_DIR_NAME);
        try {
            if (Files.exists(root) && Files.exists(operatorRoot)
                    && Files.isSameFile(root, operatorRoot)) {
                return NAME;
            }
        } catch (IOException ignored) {
            // fall through to path comparison
        }
        if (root.toAbsolutePath().normalize().equals(operatorRoot.toAbsolutePath().normalize())) {
            return NAME;
        }
        return NAME + "-" + storeFingerprint(root);
    }

    /** Stable 8-hex fingerprint of a store root path (identity, not content). */
    public static String storeFingerprint(Path storeRoot) {
        String canonical;
        try {
            canonical = storeRoot.toRealPath().toString();
        } catch (IOException e) {
            canonical = storeRoot.toAbsolutePath().normalize().toString();
        }
        try {
            var digest = java.security.MessageDigest.getInstance("SHA-256")
                    .digest(canonical.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder();
            for (int i = 0; i < 4; i++) {
                hex.append(String.format("%02x", digest[i]));
            }
            return hex.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }

    public record RegenerateResult(List<String> pluginNames, List<UnitReadProblem> problems) {
        public RegenerateResult {
            pluginNames = pluginNames == null ? List.of() : List.copyOf(pluginNames);
            problems = problems == null ? List.of() : List.copyOf(problems);
        }
    }

    /** Marketplace root directory: parent of {@code .claude-plugin/} and {@code plugins/}. */
    public Path root() {
        return store.root().resolve("plugin-marketplace");
    }

    /** Where the harness CLIs read the marketplace catalog from. */
    public Path manifestPath() {
        return root().resolve(".claude-plugin").resolve("marketplace.json");
    }

    /** Per-plugin symlink directory inside the marketplace root. */
    public Path pluginsLinkDir() {
        return root().resolve("plugins");
    }

    /**
     * Walk the installed-plugin set and rewrite the marketplace root
     * to match. Returns the list of plugin names included so callers
     * can drive harness-CLI invocations against the same set without
     * re-walking the store, plus unreadable installed-unit diagnostics.
     */
    public RegenerateResult regenerate() throws IOException {
        Fs.ensureDir(manifestPath().getParent());
        Fs.ensureDir(pluginsLinkDir());

        List<String> names = new ArrayList<>();
        var listed = store.listInstalledUnits();
        for (AgentUnit u : listed.units()) {
            if (u.kind() != UnitKind.PLUGIN) continue;
            names.add(u.name());
        }
        names.sort(String::compareToIgnoreCase);

        // Symlinks: drop any symlinks for plugins that are no longer
        // installed. Then create / refresh links for each current plugin.
        if (Files.isDirectory(pluginsLinkDir())) {
            try (var s = Files.list(pluginsLinkDir())) {
                for (Path p : (Iterable<Path>) s::iterator) {
                    String linkName = p.getFileName().toString();
                    if (!names.contains(linkName)) {
                        Fs.deleteRecursive(p);
                    }
                }
            }
        }
        // The stored link target per plugin, kept so the input record below can
        // digest the same string that was written into the tree rather than
        // re-deriving it — two derivations of one fact are two facts that can
        // disagree.
        Map<String, String> storedTargets = new LinkedHashMap<>();
        for (String name : names) {
            Path link = pluginsLinkDir().resolve(name);
            Path target = store.unitDir(name, UnitKind.PLUGIN);
            if (Files.exists(link, LinkOption.NOFOLLOW_LINKS)
                    || Files.isSymbolicLink(link)) {
                Fs.deleteRecursive(link);
            }
            Path stored = dev.skillmanager.store.HomeLinks.storedTarget(store.root(), link, target);
            try {
                // Both ends live in this home, so the link is stored
                // relative — an absolute one would make a copy of the home
                // reach back into the original.
                Files.createSymbolicLink(link, stored);
                storedTargets.put(name, stored.toString());
            } catch (UnsupportedOperationException | IOException fallback) {
                Fs.copyRecursive(target, link);
                // A copy has no link target. Recording the symlink's would be a
                // claim about a link that is not there — the entry's identity
                // half is one field short, and the digest says so by covering
                // a null the encoder skips rather than a string it invents.
                storedTargets.put(name, null);
            }
        }

        // Manifest. The schema mirrors Anthropic's
        // claude-plugins-official: each plugin entry is identified by a
        // {@code name} and a {@code source} of either
        // {@code "./relative-path"} or
        // {@code {source: local, path: "./..."}}. We use the string form,
        // which is the simplest local-path syntax both Claude and Codex
        // CLIs accept.
        Map<String, Object> manifest = new LinkedHashMap<>();
        manifest.put("$schema", "https://anthropic.com/claude-code/marketplace.schema.json");
        manifest.put("name", name());
        manifest.put("description", DESCRIPTION);
        Map<String, Object> owner = new LinkedHashMap<>();
        owner.put("name", NAME);
        manifest.put("owner", owner);
        List<Map<String, Object>> plugins = new ArrayList<>();
        List<MarketplaceInputs.Entry> inputs = new ArrayList<>();
        for (String name : names) {
            String source = "./plugins/" + name;
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("name", name);
            entry.put("source", source);
            plugins.add(entry);
            // What this pass generated the entry FROM, digested at generation
            // time. Before this, the manifest carried name and source and
            // nothing else, so "did the installed plugin set change" was never
            // asked and regeneration ran wholesale on every pass because there
            // was no way to ask it. See MarketplaceInputs for the scheme and
            // for why the record is a sidecar rather than a field here.
            String target = storedTargets.get(name);
            inputs.add(MarketplaceInputs.Entry.of(name, source, target,
                    MarketplaceInputs.fingerprintOf(name, source, target,
                            store.unitDir(name, UnitKind.PLUGIN))));
        }
        manifest.put("plugins", plugins);
        Files.writeString(manifestPath(), json.writeValueAsString(manifest) + "\n");
        // A warning, not a failure. This file is EVIDENCE about the marketplace,
        // never an input to generating one, so a read-only or full home must not
        // turn a marketplace that regenerated correctly into a failed effect and
        // an exit 1. The same rule the two other producers in this ticket
        // follow, and it was missing here.
        //
        // And it is written only when its CONTENT changed. `generatedAt` is a
        // wall clock, so writing unconditionally made this file differ on every
        // pass even when the plugin set and every digest in it were identical —
        // in a file whose whole purpose is answering "did anything change".
        // That is this ticket's own defect reproduced in its own record: the
        // class is documented idempotent and its idempotency test only ever
        // compared the manifest. Skipping the no-op write also keeps
        // `generatedAt` meaning "when this content was generated" rather than
        // "when we last ran".
        try {
            MarketplaceInputs next = MarketplaceInputs.of(name(), inputs);
            if (!next.describesSameAs(MarketplaceInputs.read(root()).orElse(null))) {
                next.write(root());
            }
        } catch (IOException e) {
            dev.skillmanager.util.Log.warn(
                    "marketplace: could not record generation inputs in %s: %s",
                    MarketplaceInputs.FILENAME, e.getMessage());
        }

        return new RegenerateResult(names, listed.problems());
    }

    /**
     * One-time cleanup of the pre-marketplace plugin layout: any plugin
     * dir/symlink left behind under {@code <agentPluginsDir>/<name>} from
     * the older direct-symlink approach. Harmless when nothing is there
     * (a fresh install), removes the stale entry otherwise so the harness
     * doesn't try to load the plugin from the wrong namespace.
     *
     * <p>Only entries matching the supplied plugin names are touched —
     * never anything the harness installed itself.
     *
     * <h2>Why this needs to know about the store (#311)</h2>
     *
     * <p>The directory it deletes from is an <em>agent</em> plugins directory,
     * derived from an agent-home environment variable.
     * {@link dev.skillmanager.agent.CodexAgent#pluginsDir()} and
     * {@link dev.skillmanager.agent.GeminiAgent#pluginsDir()} compute it as
     * {@code $CODEX_HOME/plugins} and {@code $GEMINI_HOME/plugins} — those two
     * variables ARE the config directory, not its parent, unlike
     * {@code CLAUDE_HOME}. So pointing either at a Skill Manager home makes
     * that expression the STORE's own {@code plugins/}, and this method then
     * deletes every installed plugin from it, recursively, while the install
     * that triggered it reports success.
     *
     * <p>Measured 2026-09-05: {@code CODEX_HOME=<home> skill-manager install
     * <unit>} emptied {@code <home>/plugins/} and exited 0 with nothing about
     * it in the output. Each of the two variables does it independently;
     * {@code CLAUDE_HOME} does not, because {@code ClaudeAgent} resolves
     * through a config directory that appends {@code .claude}.
     *
     * <p>So the store's own unit directories are passed in and refused. The
     * misconfiguration is still a misconfiguration — this does not make
     * {@code CODEX_HOME=<a skill-manager home>} correct — but the failure mode
     * stops being silent deletion of installed units and becomes a warning
     * that names the directory and what to do about it.
     *
     * @return the entries actually removed, so the caller can say so
     */
    public static List<Path> cleanupLegacyAgentPluginEntries(
            Path agentPluginsDir, List<String> pluginNames, SkillStore store)
            throws IOException {
        if (agentPluginsDir == null || pluginNames == null || pluginNames.isEmpty()) {
            return List.of();
        }
        if (!Files.isDirectory(agentPluginsDir)) return List.of();
        if (store != null && store.ownsUnitDirectory(agentPluginsDir)) {
            dev.skillmanager.util.Log.warn("refusing to clean legacy plugin entries from %s: that is this "
                            + "home's own unit directory, not an agent's. Check "
                            + "CODEX_HOME / GEMINI_HOME — those name the config "
                            + "directory itself, so pointing one at a Skill Manager "
                            + "home aims plugin cleanup at the store (#311).",
                    agentPluginsDir);
            return List.of();
        }
        List<Path> removed = new ArrayList<>();
        for (String name : pluginNames) {
            Path stale = agentPluginsDir.resolve(name);
            if (Files.exists(stale, LinkOption.NOFOLLOW_LINKS) || Files.isSymbolicLink(stale)) {
                Fs.deleteRecursive(stale);
                removed.add(stale);
            }
        }
        return List.copyOf(removed);
    }

}
