package dev.skillmanager.project;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import dev.skillmanager.model.AgentUnit;
import dev.skillmanager.model.UnitKind;
import dev.skillmanager.shared.util.Fs;
import dev.skillmanager.store.SkillStore;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Skill-manager-owned local marketplace that wraps every installed plugin
 * for harness CLIs ({@code claude plugin}, {@code codex plugin marketplace}).
 *
 * <p>The marketplace lives at {@code <store>/plugin-marketplace/} and is
 * one shared root for all harnesses — Claude and Codex each register the
 * same path via {@code plugin marketplace add <path>}, then their CLIs
 * read {@code .claude-plugin/marketplace.json} from inside it.
 *
 * <p>Each installed plugin is exposed as a per-plugin symlink under
 * {@code plugin-marketplace/plugins/<name>} → {@code <store>/plugins/<name>},
 * and a corresponding {@code plugins[].source} entry in
 * {@code marketplace.json} points at the relative path
 * {@code "./plugins/<name>"}. The symlink keeps the plugin bytes
 * single-source (the store) while letting the harness CLIs resolve a
 * stable layout under the marketplace root.
 *
 * <p>Regeneration is idempotent — call {@link #regenerate()} after any
 * change to the installed-plugin set and the marketplace root will end
 * up consistent: stale symlinks pruned, manifest rewritten, missing
 * symlinks recreated. Skills are ignored — the harness CLIs only deal
 * with plugins.
 */
public final class PluginMarketplace {

    /** Marketplace identifier seen by harness CLIs (plugin@<this>). */
    public static final String NAME = "skill-manager";

    private static final String DESCRIPTION =
            "Local marketplace generated by skill-manager. "
            + "Contains every plugin installed via skill-manager.";

    private final SkillStore store;
    private final ObjectMapper json = new ObjectMapper()
            .enable(SerializationFeature.INDENT_OUTPUT);

    public PluginMarketplace(SkillStore store) {
        this.store = store;
    }

    /** Marketplace root directory: parent of {@code .claude-plugin/} and {@code plugins/}. */
    public Path root() {
        return store.root().resolve("plugin-marketplace");
    }

    /** Where the harness CLIs read the marketplace catalog from. */
    public Path manifestPath() {
        return root().resolve(".claude-plugin").resolve("marketplace.json");
    }

    /** Per-plugin symlink directory inside the marketplace root. */
    public Path pluginsLinkDir() {
        return root().resolve("plugins");
    }

    /**
     * Walk the installed-plugin set and rewrite the marketplace root
     * to match. Returns the list of plugin names included so callers
     * can drive harness-CLI invocations against the same set without
     * re-walking the store.
     */
    public List<String> regenerate() throws IOException {
        Fs.ensureDir(manifestPath().getParent());
        Fs.ensureDir(pluginsLinkDir());

        List<String> names = new ArrayList<>();
        for (AgentUnit u : store.listInstalledUnits()) {
            if (u.kind() != UnitKind.PLUGIN) continue;
            names.add(u.name());
        }
        names.sort(String::compareToIgnoreCase);

        // Symlinks: drop any symlinks for plugins that are no longer
        // installed. Then create / refresh links for each current plugin.
        if (Files.isDirectory(pluginsLinkDir())) {
            try (var s = Files.list(pluginsLinkDir())) {
                for (Path p : (Iterable<Path>) s::iterator) {
                    String linkName = p.getFileName().toString();
                    if (!names.contains(linkName)) {
                        Fs.deleteRecursive(p);
                    }
                }
            }
        }
        for (String name : names) {
            Path link = pluginsLinkDir().resolve(name);
            Path target = store.unitDir(name, UnitKind.PLUGIN);
            if (Files.exists(link, LinkOption.NOFOLLOW_LINKS)
                    || Files.isSymbolicLink(link)) {
                Fs.deleteRecursive(link);
            }
            try {
                Files.createSymbolicLink(link, target);
            } catch (UnsupportedOperationException | IOException fallback) {
                Fs.copyRecursive(target, link);
            }
        }

        // Manifest. The schema mirrors Anthropic's
        // claude-plugins-official: each plugin entry is identified by a
        // {@code name} and a {@code source} of either
        // {@code "./relative-path"} or
        // {@code {source: local, path: "./..."}}. We use the string form,
        // which is the simplest local-path syntax both Claude and Codex
        // CLIs accept.
        Map<String, Object> manifest = new LinkedHashMap<>();
        manifest.put("$schema", "https://anthropic.com/claude-code/marketplace.schema.json");
        manifest.put("name", NAME);
        manifest.put("description", DESCRIPTION);
        Map<String, Object> owner = new LinkedHashMap<>();
        owner.put("name", "skill-manager");
        manifest.put("owner", owner);
        List<Map<String, Object>> plugins = new ArrayList<>();
        for (String name : names) {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("name", name);
            entry.put("source", "./plugins/" + name);
            plugins.add(entry);
        }
        manifest.put("plugins", plugins);
        Files.writeString(manifestPath(), json.writeValueAsString(manifest) + "\n");

        return names;
    }

    /**
     * One-time cleanup of the pre-marketplace plugin layout: any plugin
     * dir/symlink left behind under {@code <agentPluginsDir>/<name>} from
     * the older direct-symlink approach. Harmless when nothing is there
     * (a fresh install), removes the stale entry otherwise so the harness
     * doesn't try to load the plugin from the wrong namespace.
     *
     * <p>Only entries matching the supplied plugin names are touched —
     * never anything the harness installed itself.
     */
    public static void cleanupLegacyAgentPluginEntries(Path agentPluginsDir, List<String> pluginNames)
            throws IOException {
        if (agentPluginsDir == null || pluginNames == null || pluginNames.isEmpty()) return;
        if (!Files.isDirectory(agentPluginsDir)) return;
        for (String name : pluginNames) {
            Path stale = agentPluginsDir.resolve(name);
            if (Files.exists(stale, LinkOption.NOFOLLOW_LINKS) || Files.isSymbolicLink(stale)) {
                Fs.deleteRecursive(stale);
            }
        }
    }
}
