///usr/bin/env jbang "$0" "$@" ; exit $?
//SOURCES ../../sdk/java/src/main/java/com/hayden/testgraphsdk/sdk/*.java

import com.hayden.testgraphsdk.sdk.Node;
import com.hayden.testgraphsdk.sdk.NodeResult;
import com.hayden.testgraphsdk.sdk.NodeSpec;
import com.hayden.testgraphsdk.sdk.Procs;
import com.hayden.testgraphsdk.sdk.ProcessRecord;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Installs hello-plugin from the registry. Parallel to {@code HelloInstalled}
 * for skills, but verifies the plugin lands at {@code SKILL_MANAGER_HOME/plugins/}
 * (not {@code skills/}) — exercises the kind-aware
 * {@code CommitUnitsToStore} path, the units.lock flip, and the
 * skill-manager-owned plugin marketplace generated by the
 * {@code RefreshHarnessPlugins} effect.
 *
 * <p>The pre-marketplace approach (per-plugin symlink under
 * {@code ~/.claude/plugins/<name>}) is deliberately gone: harness CLIs
 * load plugins from a configured marketplace's {@code .claude-plugin/
 * marketplace.json}, not by scanning {@code ~/.claude/plugins/}. This
 * node asserts the new layout and that the legacy symlink is NOT
 * present.
 */
public class HelloPluginInstalled {
    static final NodeSpec SPEC = NodeSpec.of("hello.plugin.installed")
            .kind(NodeSpec.Kind.ACTION)
            .dependsOn("hello.plugin.published")
            .tags("registry", "install", "plugin")
            .timeout("60s")
            .output("pluginDir", "string")
            .output("marketplaceDir", "string");

    public static void main(String[] args) {
        Node.run(args, SPEC, ctx -> {
            String home = ctx.get("env.prepared", "home").orElse(null);
            String claudeHome = ctx.get("env.prepared", "claudeHome").orElse(null);
            String codexHome = ctx.get("env.prepared", "codexHome").orElse(null);
            String registryUrl = ctx.get("registry.up", "baseUrl").orElse(null);
            if (home == null || claudeHome == null || codexHome == null || registryUrl == null) {
                return NodeResult.fail("hello.plugin.installed", "missing upstream context");
            }

            Path repoRoot = Path.of(System.getProperty("user.dir")).resolve("..").normalize();
            Path sm = repoRoot.resolve("skill-manager");

            ProcessBuilder pb = new ProcessBuilder(
                    sm.toString(), "install", "hello-plugin",
                    "--registry", registryUrl,
                    "--yes");
            pb.environment().put("SKILL_MANAGER_HOME", home);
            pb.environment().put("SKILL_MANAGER_INSTALL_DIR", repoRoot.toString());
            pb.environment().put("CLAUDE_HOME", claudeHome);
            pb.environment().put("CODEX_HOME", codexHome);
            // CLAUDE_CONFIG_DIR is what the Claude CLI itself honors —
            // skill-manager's HarnessPluginCli.Claude driver also sets
            // it to <claudeHome>/.claude when invoking subprocesses,
            // but pre-setting it here means anything else the install
            // touches via the CLI lands inside the sandboxed harness
            // home rather than the developer's real ~/.claude.
            pb.environment().put("CLAUDE_CONFIG_DIR",
                    Path.of(claudeHome).resolve(".claude").toString());
            // hello-plugin's contained skill declares pip:ruff (CLI),
            // which gates by default — turn off the cli flag for this
            // run.
            pb.environment().put("SKILL_MANAGER_POLICY_INSTALL_REQUIRE_CONFIRMATION_FOR_CLI_DEPS", "false");

            ProcessRecord proc = Procs.run(ctx, "install", pb);
            int rc = proc.exitCode();

            // Plugin lands under plugins/ (not skills/) — kind-aware
            // CommitUnitsToStore.
            Path pluginDir = Path.of(home).resolve("plugins/hello-plugin");
            boolean manifestOk = Files.isRegularFile(pluginDir.resolve(".claude-plugin/plugin.json"));
            boolean tomlOk = Files.isRegularFile(pluginDir.resolve("skill-manager-plugin.toml"));
            boolean containedOk = Files.isRegularFile(
                    pluginDir.resolve("skills/hello-impl/SKILL.md"));

            // Lock should now have a row for hello-plugin.
            Path lockPath = Path.of(home).resolve("units.lock.toml");
            boolean lockOk = false;
            if (Files.isRegularFile(lockPath)) {
                String body = Files.readString(lockPath);
                lockOk = body.contains("name = \"hello-plugin\"") && body.contains("kind = \"plugin\"");
            }

            // skill-manager plugin marketplace — the new harness-facing
            // entry point. RefreshHarnessPlugins regenerates this dir
            // from the installed-plugin set.
            Path marketplaceDir = Path.of(home).resolve("plugin-marketplace");
            Path marketplaceManifest = marketplaceDir.resolve(".claude-plugin/marketplace.json");
            boolean marketplaceOk = Files.isRegularFile(marketplaceManifest);
            boolean marketplaceListsHelloPlugin = false;
            if (marketplaceOk) {
                String body = Files.readString(marketplaceManifest);
                marketplaceListsHelloPlugin = body.contains("\"name\" : \"hello-plugin\"")
                        && body.contains("\"./plugins/hello-plugin\"");
            }
            // Per-plugin symlink inside the marketplace points at the
            // store dir — the harness CLI resolves entries from here.
            Path marketplaceLink = marketplaceDir.resolve("plugins/hello-plugin");
            boolean marketplaceLinkOk = Files.exists(marketplaceLink, java.nio.file.LinkOption.NOFOLLOW_LINKS)
                    || Files.isSymbolicLink(marketplaceLink);

            // The pre-marketplace approach left a symlink at
            // <claudeHome>/.claude/plugins/<name> — the new layout
            // explicitly does NOT use that namespace. Assert absence so
            // a regression to the old behavior fails this node.
            Path legacyClaudeLink = Path.of(claudeHome).resolve(".claude/plugins/hello-plugin");
            boolean noLegacyLink = !Files.exists(legacyClaudeLink, java.nio.file.LinkOption.NOFOLLOW_LINKS);

            boolean pass = rc == 0 && manifestOk && tomlOk && containedOk && lockOk
                    && marketplaceOk && marketplaceListsHelloPlugin && marketplaceLinkOk
                    && noLegacyLink;
            NodeResult result = pass
                    ? NodeResult.pass("hello.plugin.installed")
                    : NodeResult.fail("hello.plugin.installed",
                            "rc=" + rc + " manifest=" + manifestOk + " toml=" + tomlOk
                                    + " contained=" + containedOk + " lock=" + lockOk
                                    + " marketplace=" + marketplaceOk
                                    + " marketplaceListsHello=" + marketplaceListsHelloPlugin
                                    + " marketplaceLink=" + marketplaceLinkOk
                                    + " noLegacyLink=" + noLegacyLink);
            return result
                    .process(proc)
                    .assertion("install_ok", rc == 0)
                    .assertion("plugin_manifest_present", manifestOk)
                    .assertion("plugin_toml_present", tomlOk)
                    .assertion("contained_skill_present", containedOk)
                    .assertion("lock_advanced", lockOk)
                    .assertion("plugin_marketplace_manifest_present", marketplaceOk)
                    .assertion("marketplace_lists_hello_plugin", marketplaceListsHelloPlugin)
                    .assertion("marketplace_plugin_symlink_present", marketplaceLinkOk)
                    .assertion("legacy_per_plugin_namespace_unused", noLegacyLink)
                    .metric("exitCode", rc)
                    .publish("pluginDir", pluginDir.toString())
                    .publish("marketplaceDir", marketplaceDir.toString());
        });
    }
}
