package dev.skillmanager.launch;

import dev.skillmanager.policy.HomePolicy;
import dev.skillmanager.shared.util.Fs;
import dev.skillmanager.store.SkillStore;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the {@code claude} / {@code codex} / {@code gemini} launchers that
 * bind a harness process to the Skill Manager home they live in.
 *
 * <h2>Nobody should have to export anything</h2>
 *
 * <p>Before this existed, {@code AgentHomes} only <em>read</em> the four
 * config-root variables and the project documentation told a human to export
 * them by hand. That is a step a person forgets and an agent cannot be asked to
 * know about, and forgetting it does not fail — it silently runs against the
 * global home. A shim on {@code PATH} makes the correct environment the
 * <em>default</em> for anything launched from a worktree.
 *
 * <h2>The shim carries no absolute path</h2>
 *
 * <p>It derives its home from its own location ({@code <home>/bin/launch/<x>}
 * → {@code <home>}) and delegates to {@code skill-manager exec}. Two
 * consequences, both deliberate:
 *
 * <ul>
 *   <li><b>Relocatable.</b> A home that is copied to a new root keeps working
 *       with no rewrite, which is the property the whole per-project-home design
 *       rests on. It is also why these do not bake in the real binary's
 *       path.</li>
 *   <li><b>One implementation of the rules.</b> {@code PATH} precedence,
 *       foreign-home pruning, the {@code CLAUDE_CONFIG_DIR} refusal and the
 *       home policy all live in {@link LaunchEnv} and are exercised by tests.
 *       A shim that assembled the environment in bash would be a second,
 *       untested copy of security-relevant logic — and it is the copy that
 *       actually runs.</li>
 * </ul>
 */
public final class LauncherShims {

    /** The harnesses a home publishes a launcher for. */
    public static final List<String> AGENTS = List.of("claude", "codex", "gemini");

    private LauncherShims() {}

    public record Result(Path dir, List<Path> written) {}

    /** {@code <store>/bin/launch}. */
    public static Path dir(SkillStore store) {
        return LaunchEnv.launcherDir(store);
    }

    /**
     * Write (or rewrite) every launcher into {@code <store>/bin/launch}.
     *
     * <p>Refused on a frozen home: the launchers are content, and a frozen home
     * is one whose contents are evidence.
     */
    public static Result write(SkillStore store) throws IOException {
        HomePolicy.requireLive(store, "home shims");
        Path dir = dir(store);
        Fs.ensureDir(dir);
        List<Path> written = new java.util.ArrayList<>();
        for (String agent : AGENTS) {
            Path file = dir.resolve(agent);
            Files.writeString(file, script(agent));
            Fs.makeExecutable(file);
            written.add(file);
        }
        return new Result(dir, List.copyOf(written));
    }

    /**
     * The launcher body for {@code agent}.
     *
     * <p>{@code SKILL_MANAGER_CLI} is honoured first so a harness that built
     * its own CLI can pin it (and so a test can substitute a stub), then the
     * home's own {@code bin/cli/skill-manager}, then {@code PATH}. The same
     * order {@code HomeDescriptor.resolveCli} uses, for the same reason: a
     * per-project home that ships a CLI means to use it.
     */
    public static String script(String agent) {
        return """
                #!/usr/bin/env bash
                # Generated by `skill-manager home shims` — do not edit.
                #
                # Launches `%1$s` bound to the Skill Manager home this shim lives in.
                # The home is derived from the shim's own location, so a cloned home
                # needs no rewrite; every rule about the launch environment (PATH
                # precedence, refusing an unredirected CLAUDE_CONFIG_DIR, the home
                # policy) is applied by `skill-manager exec`, not duplicated here.
                set -euo pipefail

                shim_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
                home="$(cd -- "$shim_dir/../.." && pwd -P)"

                cli="${SKILL_MANAGER_CLI:-}"
                if [ -z "$cli" ]; then
                  if [ -x "$home/bin/cli/skill-manager" ]; then
                    cli="$home/bin/cli/skill-manager"
                  else
                    cli="$(command -v skill-manager || true)"
                  fi
                fi
                if [ -z "$cli" ]; then
                  echo "%1$s: cannot find the skill-manager CLI for the home at $home." >&2
                  echo "  Set SKILL_MANAGER_CLI, or put skill-manager on PATH." >&2
                  exit 127
                fi

                exec "$cli" exec --home "$home" -- %1$s "$@"
                """.formatted(agent);
    }

}
