package dev.skillmanager.launch;

import dev.skillmanager.policy.HomePolicy;
import dev.skillmanager.shared.util.Fs;
import dev.skillmanager.store.SkillStore;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the {@code claude} / {@code codex} / {@code gemini} launchers that
 * bind a harness process to the Skill Manager home they live in.
 *
 * <h2>Nobody should have to export anything</h2>
 *
 * <p>Before this existed, {@code AgentHomes} only <em>read</em> the four
 * config-root variables and the project documentation told a human to export
 * them by hand. That is a step a person forgets and an agent cannot be asked to
 * know about, and forgetting it does not fail — it silently runs against the
 * global home. A shim on {@code PATH} makes the correct environment the
 * <em>default</em> for anything launched from a worktree.
 *
 * <h2>The shim carries no absolute path</h2>
 *
 * <p>It derives its home from its own location ({@code <home>/bin/launch/<x>}
 * → {@code <home>}) and delegates to {@code skill-manager exec}. Two
 * consequences, both deliberate:
 *
 * <ul>
 *   <li><b>Relocatable.</b> A home that is copied to a new root keeps working
 *       with no rewrite, which is the property the whole per-project-home design
 *       rests on. It is also why these do not bake in the real binary's
 *       path.</li>
 *   <li><b>One implementation of the rules.</b> {@code PATH} precedence,
 *       foreign-home pruning, the {@code CLAUDE_CONFIG_DIR} refusal and the
 *       home policy all live in {@link LaunchEnv} and are exercised by tests.
 *       A shim that assembled the environment in bash would be a second,
 *       untested copy of security-relevant logic — and it is the copy that
 *       actually runs.</li>
 * </ul>
 */
public final class LauncherShims {

    /** The harnesses a home publishes a launcher for. */
    public static final List<String> AGENTS = List.of("claude", "codex", "gemini");

    private LauncherShims() {}

    public record Result(Path dir, List<Path> written) {}

    /** {@code <store>/bin/launch}. */
    public static Path dir(SkillStore store) {
        return LaunchEnv.launcherDir(store);
    }

    /** {@code <store>/bin/cli/skill-manager} — the home's own CLI entrypoint. */
    public static Path cliEntrypoint(SkillStore store) {
        return store.cliBinDir().resolve(CLI).toAbsolutePath().normalize();
    }

    /** The basename both {@link #script} and {@code HomeDescriptor.resolveCli} read. */
    private static final String CLI = "skill-manager";

    /**
     * Write (or rewrite) every launcher into {@code <store>/bin/launch}.
     *
     * <p>Refused on a frozen home: the launchers are content, and a frozen home
     * is one whose contents are evidence.
     */
    public static Result write(SkillStore store) throws IOException {
        HomePolicy.requireLive(store, "home shims");
        Path dir = dir(store);
        Fs.ensureDir(dir);
        List<Path> written = new java.util.ArrayList<>();
        for (String agent : AGENTS) {
            Path file = dir.resolve(agent);
            Files.writeString(file, script(agent));
            Fs.makeExecutable(file);
            written.add(file);
        }

        // The home's own CLI entrypoint, written here because it is the same
        // category of artifact as the launchers above — a generated, relocatable
        // shim the home owns — and this is the command that owns them.
        //
        // Until now nothing wrote it, while BOTH the launcher script and
        // HomeDescriptor.resolveCli read it: a contract with two readers and no
        // writer. The observed symptom was the worst kind for a launcher, a
        // silent no-launch, so cliScript() is written to be incapable of
        // exiting 0 without having exec'd something.
        Path cli = cliEntrypoint(store);
        Fs.ensureDir(cli.getParent());
        Files.writeString(cli, cliScript());
        Fs.makeExecutable(cli);
        written.add(cli);

        return new Result(dir, List.copyOf(written));
    }

    /**
     * The launcher body for {@code agent}.
     *
     * <p>{@code SKILL_MANAGER_CLI} is honoured first so a harness that built
     * its own CLI can pin it (and so a test can substitute a stub), then the
     * home's own {@code bin/cli/skill-manager}, then {@code PATH}. The same
     * order {@code HomeDescriptor.resolveCli} uses, for the same reason: a
     * per-project home that ships a CLI means to use it.
     */
    public static String script(String agent) {
        return """
                #!/usr/bin/env bash
                # Generated by `skill-manager home shims` — do not edit.
                #
                # Launches `%1$s` bound to the Skill Manager home this shim lives in.
                # The home is derived from the shim's own location, so a cloned home
                # needs no rewrite; every rule about the launch environment (PATH
                # precedence, refusing an unredirected CLAUDE_CONFIG_DIR, the home
                # policy) is applied by `skill-manager exec`, not duplicated here.
                set -euo pipefail

                shim_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
                home="$(cd -- "$shim_dir/../.." && pwd -P)"

                cli="${SKILL_MANAGER_CLI:-}"
                if [ -z "$cli" ]; then
                  if [ -x "$home/bin/cli/skill-manager" ]; then
                    cli="$home/bin/cli/skill-manager"
                  else
                    cli="$(command -v skill-manager || true)"
                  fi
                fi
                if [ -z "$cli" ]; then
                  echo "%1$s: cannot find the skill-manager CLI for the home at $home." >&2
                  echo "  Set SKILL_MANAGER_CLI, or put skill-manager on PATH." >&2
                  exit 127
                fi

                exec "$cli" exec --home "$home" -- %1$s "$@"
                """.formatted(agent);
    }

    /**
     * The body of {@code <home>/bin/cli/skill-manager}.
     *
     * <h2>It must not find itself</h2>
     *
     * <p>{@link LaunchEnv} puts {@code <home>/bin/cli} at the FRONT of the
     * launch PATH, so a shim living there that resolved the CLI with a bare
     * {@code command -v skill-manager} would resolve to itself and spin until
     * the process table gave out. The PATH search below removes this shim's own
     * directory first, comparing physical paths so a symlinked or
     * differently-spelled {@code bin/cli} on PATH is still recognised as self —
     * {@code /var} vs {@code /private/var} has already cost this epic a bug.
     *
     * <h2>It cannot succeed without launching</h2>
     *
     * <p>Every path out of this script either {@code exec}s a real CLI or exits
     * non-zero with a diagnostic. That is the whole point of the ticket that
     * added it: the defect being fixed was a shim that printed a usage error and
     * exited 0, which reads as success to every caller and to every graph node
     * that checks an exit code.
     */
    public static String cliScript() {
        return """
                #!/usr/bin/env bash
                # Generated by `skill-manager home shims` — do not edit.
                #
                # The CLI entrypoint for the Skill Manager home this shim lives in
                # (<home>/bin/cli/skill-manager). Carries no absolute path, so a
                # home that is copied to a new root keeps working with no rewrite.
                set -euo pipefail

                self_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

                cli="${SKILL_MANAGER_CLI:-}"
                if [ -z "$cli" ]; then
                  # Search PATH with this shim's own directory removed. `exec`
                  # puts <home>/bin/cli first, so without this we find ourselves.
                  filtered=""
                  while IFS= read -r entry; do
                    [ -z "$entry" ] && continue
                    physical="$(cd -- "$entry" 2>/dev/null && pwd -P || printf '%%s' "$entry")"
                    [ "$physical" = "$self_dir" ] && continue
                    filtered="${filtered:+$filtered:}$entry"
                  done <<< "$(printf '%%s' "${PATH:-}" | tr ':' '\\n')"
                  cli="$(PATH="$filtered" command -v skill-manager || true)"
                fi

                if [ -z "$cli" ]; then
                  home="$(cd -- "$self_dir/../.." && pwd -P)"
                  echo "skill-manager: no CLI is provisioned for the home at $home." >&2
                  echo "  Set SKILL_MANAGER_CLI, or put skill-manager on PATH," >&2
                  echo "  or re-provision this home with \\`skill-manager sync --force-scripts\\`." >&2
                  exit 127
                fi

                exec "$cli" "$@"
                """;
    }

}
